In [25]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
RAW_DIR = BASE_DIR / "data" / "raw" / "movie_ticket_data" / "movie_ticket_data"

df_campaign = pd.read_csv(RAW_DIR / "campaign.csv")
df_customer = pd.read_csv(RAW_DIR / "customer.csv")
df_device = pd.read_csv(RAW_DIR / "device_detail.csv")
df_status = pd.read_csv(RAW_DIR / "status_detail.csv")
df_ticket = pd.read_csv(RAW_DIR / "ticket_history.csv")

# Customer Table

In [26]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 131400 entries, 0 to 131399
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   customer_id  131400 non-null  int64
 1   usergender   131400 non-null  str
 2   dob          131400 non-null  str
dtypes: int64(1), str(2)
memory usage: 3.0 MB

In [27]:
df_customer_clean = df_customer.copy()

In [28]:
print("customer:", df_customer_clean.shape)
df_customer_clean.info()
df_customer_clean.head(5)

customer: (131400, 3)
<class 'pandas.DataFrame'>
RangeIndex: 131400 entries, 0 to 131399
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   customer_id  131400 non-null  int64
 1   usergender   131400 non-null  str
 2   dob          131400 non-null  str
dtypes: int64(1), str(2)
memory usage: 3.0 MB

   customer_id usergender         dob
0       100032     Female    8/8/1985
1       100046       Male   7/11/1987
2       100050       Male  11/19/1994
3       100063       Male   9/10/1999
4       100076     Female   5/14/1995

In [29]:
print("Total rows:", len(df_customer_clean))

print("Unique customer_id:", df_customer_clean["customer_id"].nunique())

print("Duplicated customer_id:", df_customer_clean["customer_id"].duplicated().sum())

Total rows: 131400
Unique customer_id: 131400
Duplicated customer_id: 0

In [30]:
df_customer_clean["usergender"].value_counts(dropna=False)

usergender
Female        61401
Male          55717
Not verify    14282
Name: count, dtype: int64

In [31]:
from datetime import datetime
df_customer_clean["dob"] = pd.to_datetime(df_customer_clean["dob"],errors="coerce")

In [32]:
df_customer_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 131400 entries, 0 to 131399
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   customer_id  131400 non-null  int64
 1   usergender   131400 non-null  str
 2   dob          131400 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 3.0 MB

In [70]:
print("Min dob:", df_customer_clean["dob"].min())
print("Max dob:", df_customer_clean["dob"].max())

Min dob: 1911-12-30 00:00:00
Max dob: 2036-02-07 00:00:00

In [71]:
df_customer_clean = df_customer_clean[
    df_customer_clean["dob"] <= pd.Timestamp.today()
]

In [72]:
print("Min dob:", df_customer_clean["dob"].min())
print("Max dob:", df_customer_clean["dob"].max())

Min dob: 1911-12-30 00:00:00
Max dob: 2019-02-02 00:00:00

In [73]:
from pathlib import Path

BASE_DIR = Path.cwd().parent
PROCESSED_DIR = BASE_DIR / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

df_customer_clean.to_csv(PROCESSED_DIR / "customer_clean.csv", index=False)

# Device table

In [34]:
df_device.info()

<class 'pandas.DataFrame'>
RangeIndex: 139902 entries, 0 to 139901
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   device_number  139901 non-null  str
 1   model          132763 non-null  str
 2   platform       139902 non-null  str
dtypes: str(3)
memory usage: 3.2 MB

In [35]:
df_device_clean = df_device.copy()

In [40]:
print("device:", df_device_clean.shape)
df_device_clean.info()
df_device_clean.head(5)

device: (139902, 3)
<class 'pandas.DataFrame'>
RangeIndex: 139902 entries, 0 to 139901
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   device_number  139901 non-null  str
 1   model          132763 non-null  str
 2   platform       139902 non-null  str
dtypes: str(3)
memory usage: 3.2 MB

                      device_number        model platform
0  00006afbe30ae7018c92bb324cd58afc      browser  website
1  0000b0ce524ef4d66c7bfdad67a91970  devicemodel   mobile
2  0000e2a055b67fe49c06bbe28b268251   iPhone10,2   mobile
3  00012f7a6842cca5d531b7c8b32967d6   iPhone10,3   mobile
4  000215f1b9363b5465b8ee895fa6c920  devicemodel   mobile

In [41]:
df_device_clean = df_device_clean.dropna(subset=["device_number"])
df_device_clean["model"] = df_device_clean["model"].fillna("unknown")

In [42]:
df_device_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 139901 entries, 0 to 139900
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   device_number  139901 non-null  str
 1   model          139901 non-null  str
 2   platform       139901 non-null  str
dtypes: str(3)
memory usage: 3.2 MB

In [43]:
df_device["platform"].value_counts(dropna=False)

platform
mobile     123088
website     16814
Name: count, dtype: int64

# Status table

In [44]:
df_status.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   status_id    8 non-null      int64
 1   description  8 non-null      str
 2   error_group  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 324.0 bytes

In [45]:
df_status_clean = df_status.copy()

In [46]:
print("status", df_status_clean.shape)
df_status_clean.info()
df_status_clean.head(5)

status (8, 3)
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   status_id    8 non-null      int64
 1   description  8 non-null      str
 2   error_group  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 324.0 bytes

   status_id                                        description error_group
0          1                                   Order successful         NaN
1         -1                                    Payment overdue    customer
2         -2  Insufficient funds in customer account. Please...    customer
3         -3                         No response from your bank    external
4         -4  Password locked due to multiple incorrect atte...    customer

In [47]:
df_status_clean["error_group"] = df_status_clean["error_group"].fillna("no_error")

In [49]:
df_status_clean.head()

   status_id                                        description error_group
0          1                                   Order successful    no_error
1         -1                                    Payment overdue    customer
2         -2  Insufficient funds in customer account. Please...    customer
3         -3                         No response from your bank    external
4         -4  Password locked due to multiple incorrect atte...    customer

# Campaign table

In [50]:
df_campaign.info()

<class 'pandas.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    216 non-null    int64
 1   campaign_type  216 non-null    str
dtypes: int64(1), str(1)
memory usage: 3.5 KB

In [51]:
df_campaign_clean = df_campaign.copy()

In [52]:
print("campaign", df_campaign_clean.shape)
df_campaign_clean.info()
df_campaign_clean.head(5)

campaign (216, 2)
<class 'pandas.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    216 non-null    int64
 1   campaign_type  216 non-null    str
dtypes: int64(1), str(1)
memory usage: 3.5 KB

   campaign_id    campaign_type
0       106460  direct discount
1        30040  direct discount
2        13810          voucher
3        78370          voucher
4        83700          voucher

In [53]:
df_campaign["campaign_id"].duplicated().sum()

np.int64(0)

In [54]:
df_campaign["campaign_type"].value_counts()

campaign_type
voucher            142
direct discount     72
reward point         2
Name: count, dtype: int64

# Ticket table

In [55]:
df_ticket.info()

<class 'pandas.DataFrame'>
RangeIndex: 154827 entries, 0 to 154826
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ticket_id       154827 non-null  str
 1   customer_id     154827 non-null  int64
 2   paying_method   154827 non-null  str
 3   theater_name    154827 non-null  float64
 4   device_number   154827 non-null  str
 5   original_price  154827 non-null  float64
 6   discount_value  154827 non-null  float64
 7   final_price     154827 non-null  float64
 8   time            154827 non-null  str
 9   status_id       154827 non-null  int64
 10  campaign_id     154827 non-null  int64
 11  movie_name      154827 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 14.2 MB

In [56]:
df_ticket_clean = df_ticket.copy()

In [57]:
print("ticket", df_ticket_clean.shape)
df_ticket_clean.info()
df_ticket_clean.head(5)

ticket (154827, 12)
<class 'pandas.DataFrame'>
RangeIndex: 154827 entries, 0 to 154826
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ticket_id       154827 non-null  str
 1   customer_id     154827 non-null  int64
 2   paying_method   154827 non-null  str
 3   theater_name    154827 non-null  float64
 4   device_number   154827 non-null  str
 5   original_price  154827 non-null  float64
 6   discount_value  154827 non-null  float64
 7   final_price     154827 non-null  float64
 8   time            154827 non-null  str
 9   status_id       154827 non-null  int64
 10  campaign_id     154827 non-null  int64
 11  movie_name      154827 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 14.2 MB

,ticket_id,customer_id,paying_method,theater_name,device_number,original_price,discount_value,final_price,time,status_id,campaign_id,movie_name
0,4f5200dcdcf2396b8d50ff84bf423f32,100009,money in app,13.0,244764a57dbdeb8fe9b164847ad55183,9.90,2.10,7.80,2022-07-08 17:46:36.145,1,83330,Thor: Love And Thunder
1,07abbaf28c772692f0367ad992bb3184,100493,bank account,180.0,8fa83cf46284aafd6e5da6c96f7862b5,8.66,1.48,7.18,2022-07-15 20:44:09.952,1,83330,Thor: Love And Thunder
2,1fdbeb7eceba8a27d9d985b5b70c219a,100596,money in app,56.0,69cf9244654949047f006e441fa7a8a7,10.31,2.31,8.00,2022-07-30 11:16:55.483,1,0,Thor: Love And Thunder
3,7715c9955866bd296b98543412839abd,100852,bank account,119.0,879ed11af9d6d2b5cda4d299590735a7,27.75,1.03,26.72,2022-07-04 22:33:07.458,1,85940,Thor: Love And Thunder
4,776efd7bda0b715084430e6385f67746,100965,money in app,107.0,0a233600d993a02cc1d39fb0d87fc7de,4.33,1.03,3.30,2022-07-03 18:41:45.098,1,85940,Thor: Love And Thunder

In [59]:
print("Total rows:", len(df_ticket))
print("Unique ticket_id:", df_ticket["ticket_id"].nunique())
print("Duplicated ticket_id:", df_ticket["ticket_id"].duplicated().sum())

Total rows: 154827
Unique ticket_id: 154725
Duplicated ticket_id: 102

In [60]:
df_ticket[df_ticket["ticket_id"].duplicated(keep=False)].sort_values("ticket_id")

,ticket_id,customer_id,paying_method,theater_name,device_number,original_price,discount_value,final_price,time,status_id,campaign_id,movie_name
150887,00bbfb79541c2f026eec5bf2d1956e34,215436,debit card,160.0,3fc645d785729671153c7b12e83fe845,9.90,4.21,5.69,2022-04-12 13:05:05.904,1,73240,Jujutsu Kaisen 0
150886,00bbfb79541c2f026eec5bf2d1956e34,215436,debit card,160.0,3fc645d785729671153c7b12e83fe845,9.90,4.21,5.69,2022-04-12 13:05:05.904,1,73240,Jujutsu Kaisen 0
150826,05b8ac3f4db30400ed444142641edff1,211138,debit card,77.0,dd2a6f3c4e1694d11d764790216b5a10,10.72,5.03,5.69,2022-04-16 12:42:15.740,1,73240,Jujutsu Kaisen 0
150827,05b8ac3f4db30400ed444142641edff1,211138,debit card,77.0,dd2a6f3c4e1694d11d764790216b5a10,10.72,5.03,5.69,2022-04-16 12:42:15.740,1,73240,Jujutsu Kaisen 0
150861,05de677b48a0b8be80116ac3c66a45c4,198168,bank account,160.0,7ee73357f5954e6c6e55fc6c8f60e34b,9.90,4.58,5.32,2022-04-15 17:39:33.885,1,66390,Jujutsu Kaisen 0
...,...,...,...,...,...,...,...,...,...,...,...,...
150795,fc435b67b716c7c45995825f565bdfcc,222688,debit card,54.0,d96e86fb21e96506a2c3f8dda1fcb7c0,4.12,1.28,2.84,2022-04-15 23:16:47.777,1,73240,Jujutsu Kaisen 0
150798,fe11d769fb0a6fc3529bd4596c161326,122710,bank account,13.0,144f620b74ba09ccfe74f02daf05eac4,13.32,4.21,9.11,2022-04-15 21:14:33.176,1,73240,Jujutsu Kaisen 0
150799,fe11d769fb0a6fc3529bd4596c161326,122710,bank account,13.0,144f620b74ba09ccfe74f02daf05eac4,13.32,4.21,9.11,2022-04-15 21:14:33.176,1,73240,Jujutsu Kaisen 0
150877,ff17bb45b47f86d58aa134b896d0d8e9,191687,bank account,54.0,e3911b024474bf2cc671fda76c421efe,4.95,0.00,4.95,2022-04-12 21:22:33.719,-5,0,Jujutsu Kaisen 0
150876,ff17bb45b47f86d58aa134b896d0d8e9,191687,bank account,54.0,e3911b024474bf2cc671fda76c421efe,4.95,0.00,4.95,2022-04-12 21:22:33.719,-5,0,Jujutsu Kaisen 0

In [61]:
df_ticket_clean = df_ticket_clean.drop_duplicates()

In [62]:
df_ticket_clean.duplicated().sum()

np.int64(0)

In [63]:
df_ticket_clean["ticket_id"].duplicated().sum()

np.int64(0)

In [64]:
df_ticket_clean["time"] = pd.to_datetime(
    df_ticket_clean["time"],
    errors="coerce"
)

In [65]:
df_ticket_clean["paying_method"].value_counts(dropna=False)

paying_method
money in app    66580
bank account    52643
credit card     19820
debit card      15680
other               2
Name: count, dtype: int64

In [69]:
print("Min time:", df_ticket_clean["time"].min())
print("Max time:", df_ticket_clean["time"].max())

Min time: 2019-01-01 00:42:36.037000
Max time: 2022-12-31 23:58:51.584000

# Save data

In [74]:
from pathlib import Path

BASE_DIR = Path.cwd().parent
PROCESSED_DIR = BASE_DIR / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

df_device_clean.to_csv(PROCESSED_DIR / "device_clean.csv", index=False)
df_campaign_clean.to_csv(PROCESSED_DIR / "campaign_clean.csv", index=False)
df_status_clean.to_csv(PROCESSED_DIR / "status_clean.csv", index=False)
df_ticket_clean.to_csv(PROCESSED_DIR / "ticket_clean.csv", index=False)

print(" All cleaned data saved!")

 All cleaned data saved!

# Join tables

In [75]:
df_fact_ticket = df_ticket_clean.copy()

df_fact_ticket = df_fact_ticket.merge(
    df_customer_clean, how='left', on='customer_id'
)

df_fact_ticket = df_fact_ticket.merge(
    df_campaign_clean, how='left', on='campaign_id'
)

df_fact_ticket = df_fact_ticket.merge(
    df_status_clean, how='left', on='status_id'
)

df_fact_ticket = df_fact_ticket.merge(
    df_device_clean, how='left', on='device_number'
)

In [76]:
df_fact_ticket.isnull().sum()

ticket_id             0
customer_id           0
paying_method         0
theater_name          0
device_number         0
original_price        0
discount_value        0
final_price           0
time                  0
status_id             0
campaign_id           0
movie_name            0
usergender            2
dob                   2
campaign_type     63098
description           0
error_group           0
model                78
platform             78
dtype: int64

In [77]:
df_fact_ticket["campaign_type"] = df_fact_ticket["campaign_type"].fillna("no_campaign")
df_fact_ticket["model"] = df_fact_ticket["model"].fillna("unknown")
df_fact_ticket["platform"] = df_fact_ticket["platform"].fillna("unknown")

In [78]:
df_fact_ticket["usergender"] = df_fact_ticket["usergender"].fillna("unknown")

In [79]:
df_fact_ticket = df_fact_ticket.dropna(subset=["dob"])

In [80]:
df_fact_ticket.isnull().sum()

ticket_id         0
customer_id       0
paying_method     0
theater_name      0
device_number     0
original_price    0
discount_value    0
final_price       0
time              0
status_id         0
campaign_id       0
movie_name        0
usergender        0
dob               0
campaign_type     0
description       0
error_group       0
model             0
platform          0
dtype: int64

In [81]:
df_fact_ticket.to_csv(PROCESSED_DIR / "fact_ticket.csv", index=False)

print("fact_ticket saved")

fact_ticket saved